name: clubz
description: A Social Network for Events.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+15

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  collection: any
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.2.0
  flutter_riverpod: ^2.4.9
  get_it: ^7.2.0
  image_picker: ^1.0.4
  sliver_tools: ^0.2.8
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^2.1.0
  numberpicker: ^2.0.1
  skeleton_text: ^3.0.0
  flutter_svg: ^2.0.9
  image_cropper: ^5.0.1
  cached_network_image: ^3.2.3
  maps_launcher: ^2.0.1
  uuid: ^4.2.1
  geolocator: ^10.1.0
  super_rich_text: ^1.0.0
  beamer: ^1.5.3
  go_router: ^13.0.1
  url_launcher: ^6.1.9
  social_share: ^2.3.1
  http: ^1.1.0
  path_provider: ^2.0.12
  palette_generator: ^0.3.3+2
  app_tracking_transparency: ^2.0.3
  onesignal_flutter: 3.5.1
  flutter_image_compress: ^2.1.0
  async: ^2.9.0
  shared_preferences: ^2.0.20
  badges: ^3.0.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/adaptive_icon_background.png"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter_native_splash:
  image: assets/icons/icon.png
  color: "#000000"

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: ClubzIcons
      fonts:
        - asset: assets/ClubzIcons.ttf
  assets:
    - .env
    - assets/default_profile_picture.jpg
    - assets/default_event_picture.jpg
    - assets/icons/clubz_icon.svg
    - assets/icons/google_icon.png
    - assets/icons/instagram_icon.png
    - assets/icons/whatsapp_icon.png
